// packages/svelte/src/components/SyncCheckbox.svelte
<script lang="ts">
  import { syncField } from "../useSyncField";

  export let collection: string;
  export let docId: string;
  export let field: string;
  
  const checked = syncField<boolean>(collection, docId, field, false);

  function handleChange(event: Event) {
    const target = event.target as HTMLInputElement;
    checked.set(target.checked);
  }
</script>

<input 
  type="checkbox" 
  checked={$checked} 
  on:change={handleChange} 
  {...$$restProps}
/>

// packages/react/src/components/SyncCheckbox.tsx
import React from "react";
import { useSyncField } from "../useSyncField";

export interface SyncCheckboxProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type'> {
  collection: string;
  docId: string;
  field: string;
}

export const SyncCheckbox = React.forwardRef<HTMLInputElement, SyncCheckboxProps>(
  ({ collection, docId, field, ...props }, ref) => {
    const { value, setValue } = useSyncField<boolean>(collection, docId, field, false);

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      setValue(e.target.checked);
    };

    return (
      <input
        type="checkbox"
        ref={ref}
        checked={value}
        onChange={handleChange}
        {...props}
      />
    );
  }
);
SyncCheckbox.displayName = "SyncCheckbox";
