// packages/svelte/src/components/SyncToggle.svelte
<script lang="ts">
  import { syncField } from "../useSyncField";

  export let collection: string;
  export let docId: string;
  export let field: string;
  
  const value = syncField<boolean>(collection, docId, field, false);

  function toggle() {
    value.update(v => !v);
  }
</script>

<button 
  type="button" 
  aria-pressed={$value} 
  on:click={toggle}
  {...$$restProps}
>
  <slot value={$value}>
    {$value ? "On" : "Off"}
  </slot>
</button>

// packages/react/src/components/SyncToggle.tsx
import React from "react";
import { useSyncField } from "../useSyncField";

export interface SyncToggleProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  collection: string;
  docId: string;
  field: string;
}

export const SyncToggle = React.forwardRef<HTMLButtonElement, SyncToggleProps>(
  ({ collection, docId, field, ...props }, ref) => {
    const { value, setValue } = useSyncField<boolean>(collection, docId, field, false);

    const toggle = () => {
      setValue(!value);
    };

    return (
      <button
        type="button"
        ref={ref}
        onClick={toggle}
        aria-pressed={value}
        {...props}
      >
        {value ? "On" : "Off"}
      </button>
    );
  }
);
SyncToggle.displayName = "SyncToggle";
